// swift-tools-version: 6.0
// Auto-generated by CI — do not edit manually.

import PackageDescription

let package = Package(
    name: "SmartSpectra",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "SmartSpectra", targets: ["SmartSpectra"]),
    ],
    targets: [
        .binaryTarget(
            name: "SmartSpectra",
            url: "https://github.com/Presage-Security/SmartSpectra-Swift/releases/download/v3.4.0-rc.6/SmartSpectra.xcframework.zip",
            checksum: "acb183ca8ce5c3c9da29dc024b1498d3398601e3f7739d506153200a4543de7c"
        ),
    ]
)
