// swift-tools-version: 6.0
// Auto-generated by CI — do not edit manually.

import PackageDescription

let package = Package(
    name: "SmartSpectra",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "SmartSpectra", targets: ["SmartSpectra"]),
    ],
    targets: [
        .binaryTarget(
            name: "SmartSpectra",
            url: "https://github.com/Presage-Security/SmartSpectra-Swift/releases/download/v3.3.0-rc.7/SmartSpectra.xcframework.zip",
            checksum: "a2aaa977833d6aef4360e5937cae728eb09e665723eeaa87d8a69c711eca86ce"
        ),
    ]
)
