// swift-tools-version: 6.0
// Auto-generated by CI — do not edit manually.

import PackageDescription

let package = Package(
    name: "SmartSpectra",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "SmartSpectra", targets: ["SmartSpectra"]),
    ],
    targets: [
        .binaryTarget(
            name: "SmartSpectra",
            url: "https://github.com/Presage-Security/SmartSpectra-Swift/releases/download/v3.3.0-rc.6/SmartSpectra.xcframework.zip",
            checksum: "0bab4eb3006a3b8f899c02d2ec816f022e17903b6bca43559fd0dc0bd73f1172"
        ),
    ]
)
